### ISSUE TITLE
Cleanup datastore interface

### ISSUE THREAD

**Issue by bri365** [spiffe/spire#2199]
Remove extraneous request and response gRPC artifacts from datastore interface and replace with actual items as referred to in [PR 2178](https://github.com/spiffe/spire/pull/2178)

- [x] join token and count interfaces [PR 2178](https://github.com/spiffe/spire/pull/2178)
- [x] attested node CRUD interfaces (potentially including node selectors) #2217 
- [x] bundle CRUD interfaces PR #2231
- [x] registration entry CRUD interfaces PR #2234 
- [x] list interfaces PR #2277 
- [x] prune and update interfaces PR #2244

**Comment by azdagron** [comment]
Awesome, thanks for opening an issue to track this. I think this will be a great spot to coordinate the changes we want to make overall. #2178 is a good bite-sized PR to tackle. I think ideally we do this work over multiple PRs of similar size and scope.

I'm not sure exactly what we want to do for Entry related things that currently rely on *common.Registration entry. Ideally we have some convenient type that the *types.Entry is converted into that is passed into the datastore. We need to be very careful we keep the same URI  encoding/decoding semantics when doing so. We may also choose to hold off on changing the Entry types that go in and out of the datastore until SIG-SPEC has figured out exactly what we want to do with ID's.

**Comment by bri365** [comment]
Thanks @azdagron. I'll rename the PR and create additional ones attached to this issue. I will also keep an eye out for convenience types as I work on KV store support

**Comment by bri365** [comment]
all done!
