### ISSUE TITLE
Dynamic authorized entry cache

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#4498]
Current SPIRE authorized entry cache is a immutable data structure that is rebuilt from the database very frequently. The rebuild of  this cache causes very large database load and impedes responsiveness to event and agent registration (e.g. changes are not noticed until the cache is rebuilt). #2182 has been open for some time to come up with a better plan.

Work has been underway to to replace the authorized entry cache system with one that is dynamically adjustable based on events from the datastore. The work is currently behind a feature flag.

This issue documents the work done, and the work remaining and supersedes #2182 as a concrete plan of action.

Here are the pieces of work needed to complete the feature:

- [X] Database schema adjusted and migrations shipped (@faisal-memon, #4379)
- [X] Datastore functionality to populate and prune registration entry related events (@faisal-memon, #4411)
- [x] Datastore functionality to populate and prune agent related events (@faisal-memon, #4527)
- [X] Dynamically updatable authorized entry cache data structure (@azdagron, #4451)
- [x] Cache "hydrator" that primes the cache,  watches for datastore events, and pushes changes into the cache (@faisal-memon, #4562)
- [x] Toggle which cache to use in endpoints code based on feature flag (@faisal-memon, #4562)
- [ ] Convert feature flag into experimental flag (@faisal-memon, #4723)

**Comment by azdagron** [comment]
@faisal-memon and @edwbuck, please review :)

**Comment by faisal-memon** [comment]
Looks good to me. Thanks for putting this together. WIll get started on the agent related events early next week.

**Comment by azdagron** [comment]
#4451 has been merged. I've also updated the check list to note that #4527 is now in review.

**Comment by azdagron** [comment]
@faisal-memon, I think we need one more change to convert the feature flag into an experimental flag.

**Comment by faisal-memon** [comment]
@azdagron Sure. Would you like to do that now or after some validation?
