### ISSUE TITLE
Proposal for an alternative algorithm for events-based cache event tracking

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#5624]
The experimental events-based cache relies on tracking change events for registration entries and attested nodes. The current algorithm relies on the monotonically increasing property of the event ID. Previous assumptions around arrival order of events and event ID increment stepping have contributed to a series of fixes to the current algorithm that have complicated the codebase (e.g. skipped event discovery and tracking) and contributed to pessimistic database query load, when one of the primary goals for the events-based cache is to reduce database load in the steady state. Organizations whose deployments tickle the conditions above are not realizing as much benefit from the events-based cache as should be possible.

I propose the following algorithm change to the events based cache:
- SPIRE Server retains a list of events named `processed_events`, which is initially empty.
- Every cache poll cycle:
  1.  all events over the last `N` minutes are retrieved, based on the event CreatedAt column, into a list `recent_events`
  2.  a diff is performed against `processed_events` and `recent_events`
      -  events in `recent_events` but not in`processed_events` (i.e. new events) are processed and added to `processed_events` 
      - events in `processed_events` but not in `recent_events` (i.e. old events) are removed from `processed_events`
      - events in both `processed_events` and `recent_events` (i.e. already processed events) are ignored

This algorithm assumes a few things:
- Number of events in the last `N` minutes is manageably sized:
    Seems reasonable if we keep `N` small, e.g. 3 minutes
- No mutating transaction lives longer than `N` minutes:
    As far as I know, the only mutating operation that has the potential for a long-lived transaction is that which prunes registration entries, which executes a single statement to delete all registration entries older than some threshold. When the registration entry set is large, this operation can take some time. We can likely reduce the per-transaction time by doing the deletion in small batches.
- Event lookup by timestamp is efficient:
    The created_at column is not currently indexed, but can be.

PROS:
- No more coupling with the event ID values. The value is now a simple lookup and only has to be unique across the `N` minute window.
- Reduced database load for deployments that currently tickle large amounts skipped events in the current algorithm.
- Reaches the goal of low-to-no database load when there is no churn over registration entries/agent
- Code is much simpler.

CONS:
- Database load is not immediately reduced when there is registration entry/agent churn since we'll still poll for events for the `
N` minute window, but will fully reduce after `N` minutes.

I have prototyped the above algorithm and so far have not witnessed split brain in the cache though more testing is required.

**Comment by amoore877** [comment]
I think it'd be good to get some perf numbers between the past, current, and proposed solution.

Is this something you need spire adopters in the community or in the wild to help collect data on?

> I have prototyped the above algorithm and so far have not witnessed split brain in the cache though more testing is required.

Besides perf, reliability was also my biggest concern reading the proposal, so good that so far signs are good :)
If moving forward we should ensure having several unit and integration tests to try to tease out edge cases where locking is or is not saving us from split brain or other out-of-sync scenarios.

**Comment by azdagron** [comment]
> Is this something you need spire adopters in the community or in the wild to help collect data on?

Absolutely. I do have a local benchmark set up to evaluate reliability and perf on a simulated load (e.g. something that churns entries at some rate and occasionally pauses and asserts that the cache in two or more SPIRE servers are in sync). Real life numbers are even better.

Outside of perf, it would be invaluable to know whether or not the first two of three assumptions hold in your deployment. If you have any of the following metrics, it would be super helpful:
- Anything surrounding rate of change for registration entries/agents across a typical 24 hour period to help us understand how many events we'd be polling every poll cycle. For example, if you had a evenly distributed rate of 10 registration entries changed per second (e.g. churn of 800k workloads a day), that would be roughly 3000 events over a 5 minute period. _Outliers are of particular interest to understand the maximum._
- How long queries take to commit in your database (for all but the prune query, this could be synthesized via RPC metrics). _Outliers are again of particular interest to and determine a reasonable value for `N`._

**Comment by edwbuck** [comment]
>     * How long transactions take to commit in your database (for all but the prune transaction, this could be synthesized via RPC metrics). _Outliers are again of particular interest to determine a reasonable value for `N`._

There's no perfect answer to this, as we have very few observed items in the field that led to the failure this system was designed to fix.  Or, it is equally possible that people didn't inform me of details which were the input into the current design.  So, `N` in the current design is "the entire duration a transaction can exist".  A practical approach might permit `N` to be much smaller, but a smaller `N` comes with increasing risks that the cache and the database get out of sync and remain out of sync for long periods of time (days, or longer).

**Comment by amoore877** [comment]
Providing some numbers:

- agreed with earlier comment that there may be a bit of difficulty around specificity in time-to-commit from an RPC level and how to handle that worst case.
- - a tangential metric I can give is that replication to all read replicas is measured in millis. but this doesn't help for the longer transaction times.
- - p99 DB transaction latency is sub-second. but again, there could be outliers.
- typical day agent entry changes are so infrequent to not be considered in our case. however during a mass failover event we might see a 10k-20k burst.
- registration entry changes in a typical day are <5k distributed evenly. however during a mass failover event we aim to handle a 200k-1M burst (which we recognize results in initially degraded latencies, but it is expected to eventually "even out")

**Comment by azdagron** [comment]
> registration entry changes in a typical day are <5k distributed evenly. however during a mass failover event we aim to handle a 200k-1M burst (which we recognize results in initially degraded latencies, but it is expected to eventually "even out")

Hmm. I think that failover event blows up the first assumption "Number of events in the last N minutes is manageably sized" in a crippling way. In previous discussions I assumed that 1M registration changes were more or less distributed over a one day period (which is a reasonable ~3000 events every 5 minutes). If those registration changes are going to come in as fast as they can in the failover scenario, that number is no longer reasonable.

**Comment by edwbuck** [comment]
@amoore877 I see a lot of focus on p99 numbers.  The main issue is that anything that's below p99 works, but the failures are not statistically going to be captured by p99.

A single long-lived database transaction will be enough to cause cache synchronization issues.  If we focus on p99, then that means we only need 100 successful transactions to ignore the failing one, and our cache will still be out-of-sync.

For this reason, I don't see this as an area were statistical analysis takes precedence over a very old, traditional concept of "code correctness".  We had a system where one event outside of the p99 can break the system, and in the past we realized that saying it worked 99% of the time didn't buy sympathy for the one time it led to a running server that didn't reflect it's backing database.

That's why we treat every database change that might exist as something to consider until it _cannot_ exit.  It is an extreme point of view, but one that ensures that the cache will always be in-sync.

Should we stop polling the "might newly exist" changes at the same frequency  we poll the entire database for new records, we can reduce the impact of polling the "might newly exist" records a lot.  The previously rejected submission reduced it by 1/60th, but that was an arbitrary setting.  While I argued extensively for that solution (it had a lot of nice features, which led to its approach), any solution that polls with less frequency would be sufficient.

With the proposed approach in this Issue, any transaction that managed to live past the setting for `N` would forever be missed, and the cache would be out of sync until one of the following occurred:

1. The server is manually restarted.
2. A full cache reload is scheduled.
3. A follow up change on the same record was recorded.

The first scenario is undesirable, because there's a lot that goes on in a server restart, including denying services to the other unaffected SVIDs.

The second scenario is undesirable, because nobody is going to make the call on what the frequency of "having the right data in the cache" is.  Previous calls for this went unanswered.  Late in our analysis, it was shared with me that Uber, the reporting entity, was updating their cache once a second.  In many minds, any delays sill create failures on the Pod or process, leading to quick reloads.  However, the faster the full reload, the more we will see the benefits of the db event approach disappear.  At five seconds, it would be more efficient for the db event approach to simply not exist (but that also comes with 10,000 times more database CPU overhead).

The third scenario basically is indeterminable.  One can't surmise when the record might be updated.

For this reason, I would feel more comfortable with a _embarrassingly bad_ polling back off algorithm than re-writing the framework from scratch.  

I put too much of my social capital in attempting to get the previously rejected back off algorithm accepted.  I regret this, and to a degree, I partially see this solution as a wholesale call to disregard all lessons learned for a "simpler time".

Please do not be swayed by p99, because it means that after 100 cache updates, it's okay if your cache is out of sync once.  

I recommend that we choose any back off algorithm, even one known to be embarrassingly bad, instead of rewriting the currently existing solution which (to my knowledge) has been running error free for multiple releases.

**Comment by azdagron** [comment]
FWIW, this failover event would generate 1M skipped events to track for 12 hours (current transaction timeout value). Even with the backoff algorithm that has not yet been accepted, that would be roughly 16K queries a second for 12 hours.

**Comment by edwbuck** [comment]
@azdagron I'm ok with polling once per hour, as long as there is one poll that is guaranteed to be beyond the limit of the transaction timeout.  That said, I fully understand that the people who are going to be impacted really are the people that have the authority to set the limit.

Unfortunately, there's not limit I've ever received.  For this reason, I created a polling system that could be _configured_ to poll at any limit, in any manner (some recommended exponential backoff, some indicated that a maximum limit would be desired, and linear backoff seemed better suited to the problem).  

For this reason the backoff system I previously proposed was configurable, which made it far more complex than a non-configurable system.  The decision to make it configurable I now see as a mistake.

I recommend that we implement your previous priority queue backoff, which I don't see as optimal, but at least adding it to a correct polling approach is preferable to possibly creating a new approach that would miss database changes.  Of course, your approach uses random numbers, making it very difficult to test deterministically, but even that's better than "let's start all over again" which would likely recreate the issues that led to the solution we currently have.

**Comment by sorindumitru** [comment]
I've had a look at the two algorithms (the existing one and the new proposal) to see what we can do to make some progress on this. I think they both have some pros and cons:
* the existing algorithm has the benefit that if you don't have any skipped events, you will only process events once. So that 1M change storm will see a single spike in number of events processed. At the same time, it has to separately process the unbounded list of skipped events every refresh period which can make it slow down considerably.
* the proposed algorithm better handles the case where we have skipped events. There's no need to scan them separately, there's a single query every refresh period. But if there are lots of changes inside the lookup window, it has no choice but go through all of them again.

I wonder if it wouldn't make sense to combine the two aproaches. We can switch to something very similar to the algorithm proposed here, but instead of doing a time based lookup, we do the lookup based on event ids in the following way:
* If there's no skipped events we query based on the next expected event id, as we do now
* If there are any skipped events we query from the smallest skipped event.

The algorithm will become something like:
```
Server maintains in memory caches of:
 - skipped event ids and their timestamps
 - already processed event ids and their timestamps

Full refresh:
1. Read the last event from the database.
2. Fetch all the regsitration entries from the database
3. Initialise the internal caches to empty

Periodic updates:
1. Read events since either:
  - the last event read + 1 if there are no skipped events
  - the minimum event id from the list of skipped events
  - 0 if the caches are empty
2. If there are more than a specified threshold (to avoid large number of round trips to the database), fall back to doing a full
refresh of the cache.
3. Determine the list of skipped events and store them in the cache
4. Go through the list of retrieved events thar are not in the cache of processed events and process them and the add them to the processed events cache
5. Remove any events that have a timestamp outside the window of [now, now - "transaction timeout")

Also maintain the current logic of determining skipped events from before the first sync, to deal with that edge case.
```

It's definitely a bit more complicated that what's presented here, but if there are no skipped events it will not have a lot to process so I think there's some benefit to the extra complexity.

Additionally, independent of what algorithm we decide on, I think we need to:
* Be able to determine if we should be processing the events or if we should just do a full refresh. In the case of 1M change events proposed here, there's no point in doing an incremental update. That would currently involve 1M round trips to the database to fetch the changed entries. It would be much faster to fully hydrate the cache.
* See if it makes sense to bulk retrieve changed entries, maybe something like 100 at a time.
* Adjust the default maximum "transaction time" (quotes because it just applies to how long skipped events are maintained). I think currently it's set to the maximum default transaction time of the databases we support, but that's unlikely to happen in practice. 3 minutes also seems on the short side (probably ok for 99.999% of transactions though). Maybe we can agree on a default of 1 hour?

**Comment by MarcosDY** [comment]
@faisal-memon any suggestion about this one?

**Comment by faisal-memon** [comment]
> [@faisal-memon](https://github.com/faisal-memon) any suggestion about this one?

Looking through #5771 right now. Will circle back to this after im done with that one.

**Comment by sorindumitru** [comment]
We discussed this a bit yesterday during the contributor sync. To summarise what I remember:
* When the sync period is small (N minutes), there's probably not much practical difference between the two algorithms in terms of performance.
  * Either approach we take, we should look at decreasing the default timeout since it's unlikely for a transaction to last that long without other issues.
* One current issue with the events based cache is that it has to periodically fetch the skipped events. This adds load to the database, which goes against what we want to achieve.
  * Can be dealt with by batching fetches, to some extent
* looking back over a time window has the benefit of being able to use the read replicas for fetching events. As it is right now, with the events based cache, the read replicas are hardly used for anything.

It's likely I forgot some things, so if anyone remembers something else, please add it.

Another thing I was thinking about now was that if we do time based lookup, we might even be able to do a lookup of registration entries instead of events. We'd still need the events to be able to deal with the deleted entries, though. This has the added benefit that we remove another place we do individual fetches, the registration entries, which helps in the situation where you have a constant stream of changes.

**Comment by faisal-memon** [comment]
After thinking this over and talking to @azdagron Id like to fix up the current solution rather than refactor. The proposal to refactor may not be scalable enough when there are a large number of events to track. Changes Ill be proposing:

- [x] Reduce timeout for events from 12 hours to 15 minutes. (#5966) 
- [x] Allow events to be read from read replica (#5911)
- [x] Fetch updated registration entries in bulk (#5910) (#5970) 
- [x] Fetch updated nodes in bulk.
- [x] Add code to do a full refresh of the cache every 6 hours (https://github.com/spiffe/spire/pull/6151)

I put out the first 2 PRs for this update, referenced above. This solution will have the limitation of requiring events to have an ID that increments by 1 every time. Incrementing by more than 1 is not recommended with this solution.

Going forward to build a better system I suggest to either:
- Use the change data capture (CDC) log with SQL. That is the most reliable way of getting updates from SQL. Elasticsearch uses CDC as an example.
- Simplify the data model and access patterns to be more LRU cache friendly. This would be a larger change and maybe not possible with the way SPIRE works.
